# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e6ef1d43ef2db77e31a54d0876702d388280b023e1cbb3c30bf96b2a3796bbb577d7521735f14d5d8c46757db0f3426fea245dbf29164abc6134aa4cd40bb21

test:
  secret_key_base: 955bae3f07bfdc0e4802523eaa9bd18ccd78f9b97564bc05abb88e83732ca3278f1407fdd1eda16e717b9c118eeb248b8f36ac8983095f3abcd5c5d4d890feeb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
